<script src="/media/build.js"></script>
<link rel="stylesheet" href="/media/css/main.css" />
<div data-component="vue-app"
     data-client-guid="f51060e1c38446f0bacdf283390c37e8"
     data-client-guid-my="fc799c1399824b6f958c2f7251160ddb"
     data-hawksearch-base-api="https://dev.hawksearch.net/v9/"
     data-hawksearch-search-api="https://searchapi-dev.hawksearch.net/"
     data-index-name="">

    <div class="hawk">
        <div class="hawk__header">
            <search-box></search-box>
        </div>

        <div class="hawk__body">
            <facet-list></facet-list>

            <results></results>
        </div>

    </div>
