<?php
/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/* @var \Magento\Framework\Escaper $escaper */

use Magento\Framework\App\ActionInterface;

$om = \Magento\Framework\App\ObjectManager::getInstance();
$escaper = $om->get(\Magento\Framework\Escaper::class);
$urlHelper = $om->get(\Magento\Framework\Url\Helper\Data::class);
$urlBuilder = $om->get(\Magento\Framework\UrlInterface::class);
$request = $om->get(\Magento\Framework\App\RequestInterface::class);

$getAddTocartUrl = function () use ($urlHelper, $request, $urlBuilder)
{
    $currentUrl = $urlHelper->getEncodedUrl($urlBuilder->getCurrentUrl());
    $urlParamName = ActionInterface::PARAM_NAME_URL_ENCODED;

    $routeParams = [
        $urlParamName => $currentUrl,
        '_secure' => $request->isSecure(),
    ];
    $additional = ['_escape' => false];
    $routeParams = array_merge($routeParams, $additional);


    return $urlBuilder->getUrl('checkout/cart/add', $routeParams);
};
?>

<div id="koexample-container"></div>
<div data-bind="scope: 'koexample'">
    <!-- ko foreach: getProducts() -->
    <div><span>Product: </span><strong data-bind="text: $data.sku"></strong></div>
    <!--data-bind="attr: {'action': $data.url}"-->
    <form data-role="tocart-form"
          data-bind="attr: {'data-product-sku': $data.sku, 'action': $data.url}"
          method="post">
        <input type="hidden"
               name="product"
               data-bind="value: $data.sku">
        <input type="hidden"
               name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED ?>"
               data-bind="value: $data.url">
        <?= $block->getBlockHtml('formkey') ?>
        <button type="submit"
                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                class="action tocart primary">
            <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
        </button>
    </form>
    <!-- /ko -->

</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "koexample": {
                    "component": "HawkSearch_EsIndexing/js/koexample",
                    "template": "koexample-content",
                    "urlPart": "<?= $getAddTocartUrl(); ?>"
                }
            }
        }
    }
}
</script>

<!-- HawkSearch Vue SDK part -->

<script src="/media/hawksearch/vue/vue-hawksearch-app.js"></script>
<link rel="stylesheet" href="/media/hawksearch/vue/vue-hawksearch-app.css" />

<script id="hawksearch-config" type="application/json">
    {
        "clientGuid": "f51060e1c38446f0bacdf283390c37e8",
        "apiUrl": "https://searchapi-dev.hawksearch.net/",
        "tabConfig": {
            "alwaysOn": false
        },
        "searchConfig": {
            "scrollUpOnRefresh": false
        },
        "paramsMapping": {
            "keyword": "q"
        }
    }
</script>

<script>
    function addToCart(args) {
        // console.log(args)

        var hcParams = {
            product: '24-MB01',
            uenc: 'https://hawksearch-es-dev-m2.test/checkout/cart/add/uenc/aHR0cHM6Ly9oYXdrc2VhcmNoLWVzLWRldi1tMi50ZXN0L2NhdGFsb2dzZWFyY2gvcmVzdWx0Lz9xPXRlbnQ%2C/product/1/',
            form_key: '<?php echo $block->getLayout()->getBlock('formkey')->getFormKey(); ?>'
        }

        console.log(hcParams)

            fetch(hcParams.uenc, {
                method: 'POST',
                headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify(hcParams)
            });
        }
</script>

<script id="vue-hawksearch-result-item" type="x-template">
    <div class="hawk-results__item" @click="onClick">
        <result-image :imagePath="getField('image')"></result-image>

        <div class="hawk-results__item-name">
            <span>{{ getField('itemname') }}</span>
        </div>

        <add-to-cart :add-fn="addToCart" :add-args="{sku: getField('itemname'), url: '<?php print $getAddTocartUrl(); ?>'}" />
    </div>
</script>
