<div data-vue-hawksearch-component="searchbox" data-vue-hawksearch-config="hawksearch-config" style="width: 600px; float: right;">
    <div class="hawk">
        <div class="hawk__header">
            <search-box search-page="/catalogsearch/result"></search-box>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "hawksearchVueSDK": {}
    }
}
</script>

<script id="hawksearch-config" type="application/json">
    {
        "clientGuid": "fc799c1399824b6f958c2f7251160ddb",
        "apiUrl": "https://searchapi-dev.hawksearch.net/",
        "tabConfig": {
            "alwaysOn": false
        },
        "searchConfig": {
            "initialSearch": true,
            "scrollUpOnRefresh": false
        },
        "paramsMapping": {
            "keyword": "q"
        }
    }
</script>

<script id="vue-hawksearch-suggestion-item" type="x-template">
    <li @click="onClick">
        <img class="hawk-sqItemImage-thumb" src="https://hawksearch-es-dev-m2.test/media/catalog/product/cache/" />
        <span class="p-name">{{ getTitle() }}</span>
    </li>
</script>