<!-- CategoriesContainer component -->
<script id="vue-hawksearch-categories-container" type="x-template">
    <div v-if="suggestions && suggestions.Categories && suggestions.Categories.length">
        <h3>{{ suggestions.CategoryHeading }}</h3>
        <ul>
            <li v-for="category in suggestions.Categories" :key="category.Value" class="autosuggest-menu__item">
                <div v-html="category.Value"></div>
            </li>
        </ul>
    </div>
</script>
