<!-- SuggestionItem component -->
<script id="vue-hawksearch-suggestion-item" type="x-template">
    <li @click="onClick">
        <div class="item product product-item">
            <template v-if="getThumb('thumbnail_url')">
                <img class="hawk-sqItemImage-thumb" :src="getThumb('thumbnail_url')" />
            </template>
            <span class="p-name">{{ htmlEntityDecode(getTitle()) }}</span>
            <span v-html="hawksearch.formatItemPrice(item.Results.Document || {})"/>
        </div>
    </li>
</script>
